apiVersion: v1
kind: Service
metadata:
  namespace: ns-weatherapp
  name: weathervault-service
  labels:
    app: weathervault
spec:
  selector:
    app: weathervault
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30016
  type: NodePort
